name: Deploy Portfolio

on:
  push:
    branches:
      - main # Adjust to your repository's main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        mkdir gh-pages
        cp -r * gh-pages
        cd gh-pages
        git init
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Deploy via GitHub Actions"
        git push --force "https://${{ github.token }}@github.com/${{ github.repository }}.git" main:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
